version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pega-preco-db
    ports:
      - "6543:5432"  # Porta externa do host (6543) para a interna do container (5432)
    environment:
      POSTGRES_DB: pega-preco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: pega-preco-api
    depends_on:
      - postgres
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pega-preco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    command: ["java", "-jar", "app.jar"]
    restart: always

volumes:
  db_data:
