version: "3.8"

services:
  api:
    build: .
    container_name: fabricante-api
    ports:
      - "8085:8085"
    command: ["java", "-jar", "app.jar"]
    restart: always

    extra_hosts:
      - host.docker.internal:host-gateway